"""Audit test_solution.py integrity per case.

Two separate checks:
  (1) Was test_solution.py modified after setup wrote it?
      → byte-exact comparison against the canonical setup output
  (2) Do the official MBPP test_list assertions still appear in the file?
      → substring check; this is what actually matters for grading fairness

Source of truth for "official test_list": prompt.md, which was generated by
mbpp_task.materialize_instance() from the dataset row's test_list and is
read-only as far as the agent is concerned.

Usage:
    python -m runners.audit_tests --exp baseline
    python -m runners.audit_tests --exp baseline --json   # also write JSON
"""
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections import Counter

_PROJECT_ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
if _PROJECT_ROOT not in sys.path:
    sys.path.insert(0, _PROJECT_ROOT)

from config import WORKSHOP

CASES_DIRNAME = "single_case_details"
OUTPUT_FILENAME = "test_audit.json"


# ---------------------------------------------------------------------------
# Helpers — extract official asserts from prompt.md, rebuild canonical file
# ---------------------------------------------------------------------------

_TESTS_BLOCK_RE = re.compile(
    r"## Your code should pass these tests:\s*```python\s*\n(.*?)```",
    re.DOTALL,
)


def extract_official_tests(prompt_md: str) -> list[str]:
    """Pull the assert lines out of the ```python ... ``` block in prompt.md."""
    m = _TESTS_BLOCK_RE.search(prompt_md)
    if not m:
        return []
    block = m.group(1)
    # Each assert is on its own line; ignore blanks and inline comments
    return [
        line.strip()
        for line in block.splitlines()
        if line.strip() and not line.strip().startswith("#")
    ]


def rebuild_canonical_test_solution(test_list: list[str]) -> str:
    """Reproduce what mbpp_task.materialize_instance wrote at setup time."""
    body = "from solution import *\n\n"
    for i, t in enumerate(test_list):
        body += f"def test_case_{i}():\n    {t}\n\n"
    return body


def _norm(s: str) -> str:
    """Collapse whitespace for assert-membership check (tolerates re-indent)."""
    return re.sub(r"\s+", " ", s).strip()


# ---------------------------------------------------------------------------
# Per-case audit
# ---------------------------------------------------------------------------

def audit_case(case_dir: str) -> dict:
    case_id = os.path.basename(case_dir)
    prompt_path = os.path.join(case_dir, "prompt.md")
    test_path = os.path.join(case_dir, "test_solution.py")

    if not os.path.exists(prompt_path):
        return {"case_id": case_id, "status": "no-prompt", "reason": "prompt.md missing"}
    if not os.path.exists(test_path):
        return {"case_id": case_id, "status": "test-file-missing"}

    with open(prompt_path, "r", encoding="utf-8") as f:
        prompt_md = f.read()
    with open(test_path, "r", encoding="utf-8") as f:
        agent_test_solution = f.read()

    official_tests = extract_official_tests(prompt_md)
    if not official_tests:
        return {
            "case_id": case_id,
            "status": "no-official-tests-in-prompt",
            "reason": "couldn't parse python block in prompt.md",
        }

    canonical = rebuild_canonical_test_solution(official_tests)
    file_modified = (agent_test_solution != canonical)

    # Substring check — normalize whitespace so an agent that re-indented
    # or re-wrapped doesn't get false-flagged.
    agent_norm = _norm(agent_test_solution)
    missing = [t for t in official_tests if _norm(t) not in agent_norm]

    if not file_modified:
        status = "untouched"
    elif not missing:
        status = "modified-officials-preserved"
    elif len(missing) == len(official_tests):
        status = "officials-replaced"
    else:
        status = "officials-tampered"

    return {
        "case_id": case_id,
        "status": status,
        "file_modified": file_modified,
        "official_tests_total": len(official_tests),
        "official_tests_missing": len(missing),
        "missing_asserts": missing,
    }


# ---------------------------------------------------------------------------
# Experiment-level audit
# ---------------------------------------------------------------------------

def audit_experiment(exp_name: str, root: str = WORKSHOP) -> dict:
    cases_dir = os.path.join(root, exp_name, CASES_DIRNAME)
    if not os.path.isdir(cases_dir):
        raise FileNotFoundError(f"no cases dir at {cases_dir}")

    case_dirs = sorted(
        os.path.join(cases_dir, name)
        for name in os.listdir(cases_dir)
        if os.path.isdir(os.path.join(cases_dir, name))
    )
    per_case = [audit_case(cd) for cd in case_dirs]

    by_status = Counter(c["status"] for c in per_case)
    suspicious = [
        c for c in per_case
        if c["status"] in ("officials-tampered", "officials-replaced",
                           "test-file-missing", "no-official-tests-in-prompt")
    ]

    return {
        "exp_name": exp_name,
        "cases_total": len(per_case),
        "by_status": dict(by_status),
        "suspicious_cases": suspicious,
        "per_case": per_case,
    }


# ---------------------------------------------------------------------------
# Output formatting
# ---------------------------------------------------------------------------

_STATUS_LABEL = {
    "untouched": "untouched (file == setup output)",
    "modified-officials-preserved": "modified but official asserts still present",
    "officials-tampered": "officials partially missing/altered",
    "officials-replaced": "officials completely replaced",
    "test-file-missing": "test_solution.py was deleted",
    "no-official-tests-in-prompt": "couldn't parse prompt.md (audit unreliable)",
    "no-prompt": "prompt.md missing (cannot audit)",
}


def print_report(audit: dict) -> None:
    total = audit["cases_total"]
    print(f"\n=== Test integrity audit for exp={audit['exp_name']} ({total} cases) ===\n")

    for status, count in sorted(
        audit["by_status"].items(),
        key=lambda x: (
            0 if x[0] == "untouched" else
            1 if x[0] == "modified-officials-preserved" else 2,
            -x[1],
        ),
    ):
        label = _STATUS_LABEL.get(status, status)
        bar = "#" * min(40, int(40 * count / max(total, 1)))
        print(f"  {count:>3}  {label:<48}  {bar}")

    susp = audit["suspicious_cases"]
    if susp:
        print(f"\n--- {len(susp)} case(s) needing attention ---")
        for c in susp:
            cid = c["case_id"]
            st = c["status"]
            label = _STATUS_LABEL.get(st, st)
            extra = ""
            if c.get("official_tests_missing") is not None:
                extra = (
                    f"  ({c['official_tests_missing']}/{c['official_tests_total']} "
                    f"official asserts missing)"
                )
            print(f"  {cid}: {label}{extra}")
            for m in c.get("missing_asserts", [])[:3]:
                print(f"      missing: {m}")
    else:
        print("\nNo suspicious cases. Test grading is trustworthy.")

    # Summary verdict
    untouched_pct = audit["by_status"].get("untouched", 0) / max(total, 1) * 100
    safe_pct = (
        audit["by_status"].get("untouched", 0)
        + audit["by_status"].get("modified-officials-preserved", 0)
    ) / max(total, 1) * 100
    print(
        f"\n→ {untouched_pct:.1f}% strictly untouched · "
        f"{safe_pct:.1f}% safe for grading "
        f"(officials preserved or untouched)"
    )


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Audit test_solution.py integrity per case."
    )
    parser.add_argument("--exp", required=True, help="experiment name under Execution/")
    parser.add_argument("--root", default=WORKSHOP)
    parser.add_argument(
        "--json", action="store_true",
        help=f"also write JSON to Execution/<exp>/{OUTPUT_FILENAME}",
    )
    args = parser.parse_args()

    audit = audit_experiment(args.exp, root=args.root)
    print_report(audit)

    if args.json:
        out_path = os.path.join(args.root, args.exp, OUTPUT_FILENAME)
        with open(out_path, "w", encoding="utf-8") as f:
            json.dump(audit, f, indent=2, ensure_ascii=False)
        print(f"\nWrote audit JSON: {out_path}")


if __name__ == "__main__":
    main()
